mysite/autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name='autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.MakeView.as_view(), name='make_list'),
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),
]

mysite/cats/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name='cats'
urlpatterns = [
    path('', views.CatList.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
]

mysite/hello/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views
app_name = 'hello'

urlpatterns = [
    path('', views.hello),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('hello/',include('hello.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  
    path('autos/', include('autos.urls')),   
    path('cats/', include('cats.urls')),                
]

mysite/polls/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

mysite/autos/models.py
# Create your models here.
from django.db import models
from django.core.validators import MinLengthValidator

class Make(models.Model):
    name = models.CharField(
            max_length=200, 
            help_text='Enter a make (e.g. Dodge)',
            validators=[MinLengthValidator(2, "Make must be greater than 1 character")]
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Auto(models.Model): 
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    mileage = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    make = models.ForeignKey('Make', on_delete=models.CASCADE, null=False)

    # Shows up in the admin list
    def __str__(self):
        return self.nickname

mysite/cats/models.py
from django.db import models

# Create your models here.
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/hello/models.py
from django.db import models

# Create your models here.

mysite/home/models.py
from django.db import models

# Create your models here.

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/autos/views.py
#from dataclasses import fields
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from autos.models import Auto, Make
#from autos.forms import MakeForm

class MainView(LoginRequiredMixin, View) :
    def get(self, request):
        mc = Make.objects.all().count()
        al = Auto.objects.all()

        ctx = { 'make_count': mc, 'auto_list': al }
        return render(request, 'autos/auto_list.html', ctx)

class MakeView(LoginRequiredMixin, View) :
    def get(self, request):
        ml = Make.objects.all()
        ctx = { 'make_list': ml }
        return render(request, 'autos/make_list.html', ctx)

class MakeCreate(LoginRequiredMixin,CreateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class MakeUpdate(LoginRequiredMixin, UpdateView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class MakeDelete(LoginRequiredMixin, DeleteView):
    model = Make
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

class AutoCreate(LoginRequiredMixin,CreateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class AutoUpdate(LoginRequiredMixin, UpdateView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')


class AutoDelete(LoginRequiredMixin, DeleteView):
    model = Auto
    fields = '__all__'
    success_url = reverse_lazy('autos:all')

mysite/cats/views.py
# Create your views here.
#from dataclasses import fields
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from cats.models import Breed, Cat

class CatList(LoginRequiredMixin, View):
    def get(self, request):
        bc=Breed.objects.all().count()
        cl=Cat.objects.all()

        ctx = { 'breed_count': bc, 'cat_list':cl }
        return render(request, 'cats/cat_list.html',ctx)

class BreedView(LoginRequiredMixin, View):
    def get(self, request):
        bl= Breed.objects.all()
        ctx = { 'breed_list': bl }
        return render(request, 'cats/breed_list.html', ctx)

class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

mysite/hello/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def hello(request) :
    num_visits = request.session.get('num_visits', 0) + 1
    request.session['num_visits'] = num_visits
    if num_visits > 4 : del(request.session['num_visits'])
    return HttpResponse('view count='+str(num_visits))

mysite/home/views.py
from django.shortcuts import render

# Create your views here.

mysite/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

mysite/autos/templates/autos/auto_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/autos/templates/autos/auto_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/autos/templates/autos/auto_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Auto List</h1>
  {% if auto_list %}
  <ul>
    {% for auto in auto_list %}
      <li>
          {{ auto.nickname }} ({{ auto.make }})
          (<a href="{% url 'autos:auto_update' auto.id %}">Update</a> |
          <a href="{% url 'autos:auto_delete' auto.id %}">Delete</a>) <br/>
          {{ auto.comments }} ({{ auto.mileage }} miles)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no autos in the library.</p>
  {% endif %}
  <p>
    {% if make_count > 0 %}
      <a href="{% url 'autos:auto_create' %}">Add an auto</a>
    {% else %}
      Please add a make before you add an auto.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'autos:make_list' %}">View makes</a> ({{ make_count }}) | 
    <a href="{% url 'autos:make_create' %}">Add a make</a>
  </p>
{% endblock %}

mysite/autos/templates/autos/make_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Make</h1>

<p>Are you sure you want to delete the make: {{ make }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/autos/templates/autos/make_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/autos/templates/autos/make_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Make List</h1>
  {% if make_list %}
  <ul>
    {% for make in make_list %}
      <li>
          {{ make.name }}
         (<a href="{% url 'autos:make_update' make.id %}">Update</a> |
          <a href="{% url 'autos:make_delete' make.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no makes in the library.</p>
  {% endif %}
  <p><a href="{% url 'autos:make_create' %}">Add a make</a></p>
  <p>
    <a href="{% url 'autos:all' %}">Back to autos</a>
  </p>
{% endblock %}

mysite/cats/templates/cats/breed_confirm_delete.html
<head>
  <meta name="dj4e" content="2b7b5318ef74068608a5e88c898062c3"> 
</head>
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/cats/templates/cats/breed_form.html
<head>
  <meta name="dj4e" content="2b7b5318ef74068608a5e88c898062c3"> 
</head>
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/cats/templates/cats/breed_list.html
<head> <meta name="dj4e" content="2b7b5318ef74068608a5e88c898062c3"> </head>
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Breed List</h1>
  {% if breed_list %}
  <ul>
    {% for breed in breed_list %}
      <li>
          {{ breed.name }}
         (<a href="{% url 'cats:breed_update' breed.id %}">Update</a> |
          <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no Breeds in the library.</p>
  {% endif %}
  <p><a href="{% url 'cats:breed_create' %}">Add a Breed</a></p>
  <p>
    <a href="{% url 'cats:all' %}">Back to cats</a>
  </p>
{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
<head>
  <meta name="dj4e" content="2b7b5318ef74068608a5e88c898062c3"> 
</head>
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Cat</h1>

<p>Are you sure you want to delete the cat: {{ cat }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/cats/templates/cats/cat_form.html
<head><meta name="dj4e" content="2b7b5318ef74068608a5e88c898062c3"> </head>
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/cats/templates/cats/cat_list.html
<head><meta name="dj4e" content="2b7b5318ef74068608a5e88c898062c3"> </head>
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Cats List</h1>
  {% if cat_list %}
  <ul>
    {% for cat in cat_list %}
      <li>
          {{ cat.nickname }} ({{ cat.breed }})
          (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> |
          <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>) <br/>
          {{ cat.foods }} ({{ cat.weight }} kg)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no cats in the library.</p>
  {% endif %}
  <p>
    {% if breed_count > 0 %}
      <a href="{% url 'cats:cat_create' %}">Add a cat</a>
    {% else %}
      Please add a Breed before you add a Cat.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'cats:breed_list' %}">View breeds</a> ({{ breed_count }}) |
    <a href="{% url 'cats:breed_create' %}">Add a breed</a>
  </p>
{% endblock %}

mysite/home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->

<meta name="dj4e" content="2b7b5318ef74068608a5e88c898062c3"> 
<meta name="dj4e-code" content="42164449317930">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2021-12-22">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

mysite/home/templates/home/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
    <h1> Hello World</h1>
    <ul>
        <li><p><a href="/polls">A Polls Application</a></p></li>
        <li><p><a href="/hello">Test the session</a></p></li>
        <li><a href="/autos">Autos CRUD</a>
        <li><a href="/cats">Cats CRUD</a>
    </ul>
    
</body>
</html>